### PR TITLE
update dependencies and extend path/query/fragment special character support

### LINKED ISSUE #22: Allow redirecting to HTML anchors
`foo.bar.example.org => www.example.org/#foo.bar`

Can this be achieved?

### LINKED ISSUE #39: Allow redirects to specific port
subdomain.mydomain.com => www.mydomain.com:8080
possibly something like
www.mydomain.com.opts-port.8080.redirect.center

### PR DESCRIPTION
**Pull request by tmackay-cenet**
fixes #39 with .opts-port-<number>. option
fixes #22 with .opts-hash. option

also adds support for some common special characters including '%' to allow for URL encoding others and shorthand representation for longer URLs (maintaining backwards compatibility):

'/' => .opts-slash. (._s.)
'?' or & => .opts-query. (._q.)
'=' => .opts-eq. (._e.)
'%' => .opts-percent. (._pc.)
'+' => .opts-plus. (._p.)
':' => .opts-colon. (._c.)
'#' => .opts-hash. (._h.)
'.' => .opts-dot. (._d.)

fixes formatting to prevent eslint complaining on test

fixes and adds some test cases to improve code coverage

updates dependencies

removes deprecated dependencies
all-contributors
There is now a GitHub Bot for automating the maintenance of your contributors table https://github.com/all-contributors/all-contributors-bot

codacy-coverage
Package being deprecated in favor of https://github.com/codacy/codacy-coverage-reporter

opencollective
Depends on deprecated version of core-js with a number of issues

### CODE REVIEW

**Comment by udleinati** [comment]
Hi @tmackay-cenet thanks for the PR and sorry for my long delay to check it. Unfortunately, it's getting conflict now. Could you please check? I merged your PR #40. best

**Comment by tmackay-cenet** [comment]
Hi @udleinati, PR #40 was one of @mike1808's, and is somewhat of incompatible as it introduces a completely different URL encoding scheme which is not backwards compatible with previous versions. Additional logic could be added to detect which encoding scheme has been used, I suppose, but I'm not a fan of the base32 scheme due to size constraints (63 bytes for DNS label names and 253 bytes for the whole thing). Once you get up to including a query string this leaves very little headroom. In practice I quickly encountered CNAMEs that were too long. This PR would override the new base32 scheme as is.

**Comment by udleinati** [comment]
@tmackay-cenet my mistake during the merge. I'll create backward compatibility today or tomorrow morning. I don't think it's a good idea to add a new encoding type, redirect.center already has people using the base32 encoded query string.

**Comment by matbrgz** [comment]
Updates?

**Comment by udleinati** [comment]
I'm closing this issue. Redirect.center was fully refactored on top of nestjs and this pr won't work anymore. The issues might be solved using opts-port or opts-query/base32 options. I'm going to change the url builder to make it easier to understand.

**Pull request closed without merging**
